### ISSUE TITLE
[Question] What is the correct update site to use ?

### ISSUE THREAD

**Issue by gayanper** [eclipse/ajdt#7]
Thanks for keeping live this nice plugin.

I see that there are no updates on https://www.eclipse.org/ajdt/. But this repo under the eclipse github org seems to have latest changes. Where is the update site for new releases of AJDT ?

Could we update the Eclipse project place referring to here and to the new update site ?

**Comment by kriegaex** [comment]
You are asking on a good day, because today I have just released AspectJ 1.9.9 for Java 18 and also a few minutes ago an update site for Eclipse 4.23 containing AspectJ 1.9.9.

Please look here for a list of AJDT update sites:
https://github.com/eclipse/org.aspectj/blob/master/docs/developer/IDE.md#eclipse

Please also check the rest of the article for more information about setting up a development environment and which tools to use.

**Comment by gayanper** [comment]
Thanks alot

**Comment by basilevs** [comment]
AJDT compatible with Eclipse 2026-03 can be installed  from https://download.eclipse.org/tools/ajdt/439/dev/update
See #77

**Comment by kriegaex** [comment]
@basilevs, updating https://github.com/eclipse-aspectj/aspectj/blob/master/docs/developer/IDE.md#aspectj-development-tools-ajdt might be a better idea than posting information in an old, closed issue. 😉
